CREATE TABLE IF NOT EXISTS programs (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(120) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  body_copy JSONB NOT NULL DEFAULT '[]'::jsonb,
  hero_image_url VARCHAR(500),
  hero_image_alt VARCHAR(255),
  card_icon VARCHAR(20) DEFAULT '●',
  card_summary TEXT,
  page_url VARCHAR(255),
  cta_label VARCHAR(255),
  cta_url VARCHAR(255),
  status VARCHAR(60) NOT NULL DEFAULT 'Active',
  status_label VARCHAR(120),
  status_detail TEXT,
  hero_stats JSONB NOT NULL DEFAULT '[]'::jsonb,
  feature_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  objectives JSONB NOT NULL DEFAULT '[]'::jsonb,
  activities JSONB NOT NULL DEFAULT '[]'::jsonb,
  beneficiaries JSONB NOT NULL DEFAULT '[]'::jsonb,
  locations JSONB NOT NULL DEFAULT '[]'::jsonb,
  timeline JSONB NOT NULL DEFAULT '[]'::jsonb,
  gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
  impact_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
  stories JSONB NOT NULL DEFAULT '[]'::jsonb,
  reports JSONB NOT NULL DEFAULT '[]'::jsonb,
  partners JSONB NOT NULL DEFAULT '[]'::jsonb,
  seo_title VARCHAR(255),
  seo_description TEXT,
  display_order INT NOT NULL DEFAULT 0,
  is_featured BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  updated_by INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_programs_is_active
  ON programs (is_active);

CREATE INDEX IF NOT EXISTS idx_programs_display_order
  ON programs (display_order ASC);

CREATE INDEX IF NOT EXISTS idx_programs_status
  ON programs (status);

INSERT INTO programs (
  slug,
  title,
  summary,
  description,
  body_copy,
  hero_image_url,
  hero_image_alt,
  card_icon,
  card_summary,
  page_url,
  cta_label,
  cta_url,
  status,
  status_label,
  status_detail,
  hero_stats,
  feature_items,
  objectives,
  activities,
  beneficiaries,
  locations,
  timeline,
  gallery,
  impact_metrics,
  stories,
  reports,
  partners,
  seo_title,
  seo_description,
  display_order,
  is_featured,
  is_active
)
SELECT *
FROM (
  VALUES
    (
      'edu4all',
      'Edu4All',
      'Humanitarian education and child protection for displaced and underserved children across Nigeria.',
      'Edu4All strengthens humanitarian education, child protection, and safeguarding systems in underserved and crisis-affected settings.',
      '["We combine innovation, community action, and policy-aligned interventions to ensure no child is left behind.","The program focuses on practical support that helps children return to learning and helps caregivers navigate crisis with dignity."]'::jsonb,
      './assets/images/education 1.jpg',
      'Children learning together in a classroom supported by Edu4All',
      '📖',
      'Humanitarian education and child protection.',
      'edu4all.html',
      'Support Edu4All',
      'donate.html',
      'Active',
      'Current focus',
      'Education access, protection, and caregiver support.',
      '[{"value":"2,400+","label":"Children enrolled"},{"value":"32","label":"Communities served"},{"value":"180","label":"Teachers trained"}]'::jsonb,
      '[{"title":"School Enrollment","summary":"Direct enrollment support for displaced children."},{"title":"Learning Materials","summary":"Books, uniforms, and supplies for students."},{"title":"Child Protection","summary":"Safeguarding systems and referral pathways."},{"title":"Parent Empowerment","summary":"Livelihood support for caregiver families."}]'::jsonb,
      '[{"title":"Increase access","summary":"Help children return to school and stay enrolled."},{"title":"Protect children","summary":"Strengthen safeguarding and referral pathways."},{"title":"Support households","summary":"Pair education support with caregiver empowerment."}]'::jsonb,
      '[{"title":"Enrollment drives","summary":"Community-level outreach and registration support."},{"title":"Protection referrals","summary":"Link families to safe services when needed."},{"title":"Learning support","summary":"Supply distribution and classroom assistance."}]'::jsonb,
      '[{"title":"Children","summary":"Children in crisis-affected communities."},{"title":"Caregivers","summary":"Parents and guardians supporting school attendance."},{"title":"Teachers","summary":"Educators and facilitators in local learning spaces."}]'::jsonb,
      '[{"title":"Kaduna State","summary":"A key area for community-based outreach."},{"title":"Host communities","summary":"Locations supporting displaced families."}]'::jsonb,
      '[{"year":"2025","title":"Program launch","summary":"Edu4All launched as a response to education gaps in crisis-affected communities."},{"year":"2026","title":"Expanded enrollment","summary":"The program continues to support access, protection, and caregiver support."}]'::jsonb,
      '[{"url":"./assets/images/education 1.jpg","alt":"Children in a learning space"},{"url":"./assets/images/education  3.jpg","alt":"Classroom learning activity"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM.jpeg","alt":"Community education engagement"}]'::jsonb,
      '[{"label":"People reached","value":"14,000+"},{"label":"Communities reached","value":"32"},{"label":"Teachers trained","value":"180"}]'::jsonb,
      '[{"quote":"I am beyond happy to see my son enrolled in school and to have received empowerment to start a business.","attribution":"Edu4All Beneficiary, Saminaka Community"}]'::jsonb,
      '[{"title":"Community education plan","url":"./assets/images/PROPOSED PLAN OF ACTION FOR 2026 COMMUNITY OUTREACH (1).pdf","description":"Current education and outreach priorities."}]'::jsonb,
      '[{"title":"UNICEF"},{"title":"GIZ"},{"title":"Ministry of Environment Kaduna State"}]'::jsonb,
      'Edu4All | White Impact Development Initiative',
      'Humanitarian education and child protection for displaced and underserved children across Nigeria.',
      1,
      TRUE,
      TRUE
    ),
    (
      'blood-donation',
      'Blood Donation',
      'SRHR, safeguarding, and anti-GBV action through community accountability and healthcare access.',
      'Blood Donation centers community education, safeguarding, and survivor-centered support around health and rights.',
      '["Beyond the act of giving, community involvement and public education are crucial.","We advance the principle that access to safe blood and quality care is a fundamental human right."]'::jsonb,
      './assets/images/donation 6.jpg',
      'Community health and rights engagement',
      '🛡️',
      'SRHR, safeguarding, and anti-GBV action.',
      'blood-donation.html',
      'Support This Program',
      'donate.html',
      'Active',
      'Current focus',
      'Health rights, protection, and survivor support.',
      '[{"value":"3,200+","label":"Participants reached"},{"value":"45","label":"Community facilitators"},{"value":"28","label":"Referral partners"}]'::jsonb,
      '[{"title":"SRHR Education","summary":"Comprehensive reproductive health and rights training."},{"title":"Anti GBV Action","summary":"Prevention, response, and survivor support systems."},{"title":"FGM Elimination","summary":"Legal frameworks and community elimination strategies."},{"title":"Referral Pathways","summary":"Connected support services for survivors."}]'::jsonb,
      '[{"title":"Protect survivors","summary":"Create safer spaces and referral pathways."},{"title":"Advance rights","summary":"Expand understanding of SRHR and bodily autonomy."},{"title":"Shift norms","summary":"Use community education to drive prevention."}]'::jsonb,
      '[{"title":"Community dialogues","summary":"Rights-based education with local partners."},{"title":"Referral mapping","summary":"Connect households to available services."},{"title":"Advocacy outreach","summary":"Bring safeguarding issues into public conversation."}]'::jsonb,
      '[{"title":"Adolescents","summary":"Young people and teens accessing SRHR education."},{"title":"Women and girls","summary":"Community members at risk of GBV or exclusion."},{"title":"Frontline facilitators","summary":"Community-based educators and referral partners."}]'::jsonb,
      '[{"title":"Kaduna State","summary":"Local delivery and coordination base."},{"title":"Community centers","summary":"Spaces for dialogue and protection outreach."}]'::jsonb,
      '[{"year":"2025","title":"Community activation","summary":"Program conversations began around safeguarding and rights."},{"year":"2026","title":"Referral network growth","summary":"The work continues to expand protection and health pathways."}]'::jsonb,
      '[{"url":"./assets/images/donation 6.jpg","alt":"Community health outreach session"},{"url":"./assets/images/donation 1.jpg","alt":"Program engagement with community members"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.51 PM.jpeg","alt":"Community awareness activity"}]'::jsonb,
      '[{"label":"Participants reached","value":"3,200+"},{"label":"Community facilitators","value":"45"},{"label":"Referral partners","value":"28"}]'::jsonb,
      '[{"quote":"The community involvement has helped people understand rights and where to seek support.","attribution":"Local partner"}]'::jsonb,
      '[{"title":"Program brief","url":"./assets/images/PROPOSED PLAN OF ACTION FOR 2026 COMMUNITY OUTREACH (1).pdf","description":"Current priorities for health and rights outreach."}]'::jsonb,
      '[{"title":"Ministry of Environment Kaduna State"},{"title":"GIZ"},{"title":"Community referral partners"}]'::jsonb,
      'Blood Donation | White Impact Development Initiative',
      'SRHR, safeguarding, and anti-GBV action through community accountability and healthcare access.',
      2,
      TRUE,
      TRUE
    ),
    (
      'nextgen-civic-lab',
      'NextGen Civic Action Lab',
      'Youth civic accountability and good governance program focused on transparency, participation, and ethical leadership.',
      'NextGen Civic Action Lab builds youth civic accountability networks that hold institutions accountable and amplify community voices.',
      '["Participants learn practical monitoring tools and community advocacy methods.","The program connects grassroots action to policy spaces and public decision-making."]'::jsonb,
      './assets/images/nextGen.jpeg',
      'Young people leading civic engagement activities',
      '🏛️',
      'Youth civic accountability and governance.',
      'nextgen-civic-lab.html',
      'Support NextGen Lab',
      'donate.html',
      'Active',
      'Current focus',
      'Transparency, participation, and good governance.',
      '[{"value":"680+","label":"Youth leaders trained"},{"value":"15","label":"Accountability networks"},{"value":"40","label":"Community projects launched"}]'::jsonb,
      '[{"title":"Social Monitoring","summary":"Community based tracking of public services."},{"title":"Transparency Advocacy","summary":"Open data and accountability campaigns."},{"title":"Ethical Leadership","summary":"Values based leadership development."},{"title":"Policy Engagement","summary":"Connecting grassroots voices to policy spaces."}]'::jsonb,
      '[{"title":"Build leadership","summary":"Equip youth with monitoring and advocacy tools."},{"title":"Strengthen voices","summary":"Help communities speak into public systems."},{"title":"Improve accountability","summary":"Support local oversight and public reporting."}]'::jsonb,
      '[{"title":"Training labs","summary":"Workshops on civic accountability and monitoring."},{"title":"Community projects","summary":"Small-scale civic actions led by participants."},{"title":"Policy dialogues","summary":"Engagement with public institutions and advocates."}]'::jsonb,
      '[{"title":"Youth leaders","summary":"Young people driving civic participation."},{"title":"Community members","summary":"Residents impacted by governance and public services."},{"title":"Public institutions","summary":"Government and accountability stakeholders."}]'::jsonb,
      '[{"title":"Kaduna State","summary":"A key base for civic training and partnerships."},{"title":"Community forums","summary":"Public spaces for dialogue and action."}]'::jsonb,
      '[{"year":"2025","title":"Civic convening","summary":"The lab convened youth-led accountability conversations."},{"year":"2026","title":"Network expansion","summary":"Networks and participation continue to grow across communities."}]'::jsonb,
      '[{"url":"./assets/images/nextGen.jpeg","alt":"Young people taking part in civic learning"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM (1).jpeg","alt":"Community accountability engagement"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM (2).jpeg","alt":"Youth civic discussion"}]'::jsonb,
      '[{"label":"Youth leaders trained","value":"680+"},{"label":"Networks formed","value":"15"},{"label":"Community projects","value":"40"}]'::jsonb,
      '[{"quote":"I now know how to question public decisions and work with my peers to improve services.","attribution":"NextGen participant"}]'::jsonb,
      '[{"title":"Civic action brief","url":"./assets/images/PROPOSED PLAN OF ACTION FOR 2026 COMMUNITY OUTREACH (1).pdf","description":"Current program priorities and advocacy directions."}]'::jsonb,
      '[{"title":"Community partners"},{"title":"Public accountability groups"}]'::jsonb,
      'NextGen Civic Action Lab | White Impact Development Initiative',
      'Youth civic accountability and good governance program focused on transparency, participation, and ethical leadership.',
      3,
      TRUE,
      TRUE
    ),
    (
      'nextgen-ai',
      'NextGen AI',
      'Ethical, inclusive, and responsible AI for social equity, data rights, and community participation.',
      'NextGen AI ensures underserved communities are not left behind in the AI revolution.',
      '["We advance data rights, promote algorithmic fairness, improve accessibility, and enable community participation in technology governance.","The program makes emerging technologies easier to understand, question, and shape."]'::jsonb,
      './assets/images/ai gen.jpeg',
      'Artificial intelligence and digital inclusion concept image',
      '🤖',
      'Ethical, inclusive, and responsible AI for social equity.',
      'nextgen-ai.html',
      'Explore NextGen AI',
      './assets/images/2024-wttc-introduction-to-ai.pdf',
      'Active',
      'Current focus',
      'Digital rights, AI literacy, and inclusive innovation.',
      '[{"value":"5,721+","label":"Young people trained"},{"value":"14","label":"AI learning sessions"},{"value":"9","label":"Communities engaged"}]'::jsonb,
      '[{"title":"Data Rights Advocacy","summary":"Community ownership and protection of personal data."},{"title":"Algorithmic Fairness","summary":"Bias detection and inclusive AI design principles."},{"title":"AI Literacy","summary":"Community workshops on understanding and using AI."},{"title":"Policy Engagement","summary":"National and global AI governance participation."}]'::jsonb,
      '[{"title":"Demystify AI","summary":"Make AI understandable for non-technical audiences."},{"title":"Protect rights","summary":"Center fairness, accessibility, and community control."},{"title":"Create opportunity","summary":"Link young people to digital pathways and tools."}]'::jsonb,
      '[{"title":"Training sessions","summary":"Workshops on responsible AI and data rights."},{"title":"Community labs","summary":"Practical sessions to test ideas and tools."},{"title":"Policy dialogue","summary":"Engagement on emerging tech governance."}]'::jsonb,
      '[{"title":"Youth learners","summary":"Young people building digital literacy and confidence."},{"title":"Community leaders","summary":"Local voices shaping responsible AI discussions."},{"title":"Policy actors","summary":"Institutions influencing technology governance."}]'::jsonb,
      '[{"title":"Kaduna State","summary":"Primary community learning base."},{"title":"Online spaces","summary":"Digital learning and engagement reach wider audiences."}]'::jsonb,
      '[{"year":"2024","title":"Concept development","summary":"The initiative emerged from conversations on AI and social equity."},{"year":"2026","title":"Responsibility work","summary":"Training and advocacy continue to expand across communities."}]'::jsonb,
      '[{"url":"./assets/images/ai gen.jpeg","alt":"AI learning and design concept"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM.jpeg","alt":"Community digital learning"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.51 PM.jpeg","alt":"Youth digital advocacy"}]'::jsonb,
      '[{"label":"Young people trained","value":"5,721+"},{"label":"AI sessions","value":"14"},{"label":"Communities engaged","value":"9"}]'::jsonb,
      '[{"quote":"The session helped us understand AI as something we can question and shape, not just consume.","attribution":"NextGen AI participant"}]'::jsonb,
      '[{"title":"AI learning brief","url":"./assets/images/2024-wttc-introduction-to-ai.pdf","description":"Current learning and advocacy material."}]'::jsonb,
      '[{"title":"Digital learning communities"},{"title":"Technical collaborators"}]'::jsonb,
      'NextGen AI | White Impact Development Initiative',
      'Ethical, inclusive, and responsible AI for social equity, data rights, and community participation.',
      4,
      TRUE,
      TRUE
    ),
    (
      'creative-lab',
      'Creative Lab',
      'Media production, storytelling, and creative advocacy that amplifies community voices.',
      'Creative Lab empowers young creatives to produce documentaries, podcasts, graphic campaigns, and social media content that raise awareness and move people to act.',
      '["We provide equipment, training, and platforms to share community stories with the world.","Creative production helps young people advocate for the issues they care about."]'::jsonb,
      './assets/images/creative-lab.jpeg',
      'Creative production and storytelling workspace',
      '🎬',
      'Media production and creative advocacy.',
      'creative-lab.html',
      'Join the Lab',
      'work-with-us.html',
      'Active',
      'Current focus',
      'Storytelling, media production, and advocacy.',
      '[{"value":"45,000+","label":"Social engagements"},{"value":"12","label":"Creative workshops"},{"value":"6","label":"Fellowships"}]'::jsonb,
      '[{"title":"Media Production","summary":"Video, audio, and photography training."},{"title":"Storytelling Workshops","summary":"Narrative skills for advocacy and awareness."},{"title":"Social Campaigns","summary":"Digital campaigns that amplify community voices."},{"title":"Creative Fellowships","summary":"Residencies for emerging artists and storytellers."}]'::jsonb,
      '[{"title":"Tell community stories","summary":"Create media that centers lived experience."},{"title":"Grow creative skills","summary":"Give young creators tools and mentorship."},{"title":"Amplify advocacy","summary":"Turn stories into campaigns for change."}]'::jsonb,
      '[{"title":"Content production","summary":"Planning and creating media assets."},{"title":"Training cohorts","summary":"Learning sessions for emerging creators."},{"title":"Distribution support","summary":"Getting stories into the public conversation."}]'::jsonb,
      '[{"title":"Young creators","summary":"Media makers and storytellers."},{"title":"Community voices","summary":"People and groups sharing lived experiences."},{"title":"Advocacy partners","summary":"Organizations that amplify the work."}]'::jsonb,
      '[{"title":"Kaduna State","summary":"Creative production base."},{"title":"Digital channels","summary":"Social and web platforms for distribution."}]'::jsonb,
      '[{"year":"2025","title":"Creative launch","summary":"The lab began supporting media production and storytelling."},{"year":"2026","title":"Expanded visibility","summary":"Creative campaigns continue to grow across channels."}]'::jsonb,
      '[{"url":"./assets/images/creative-lab.jpeg","alt":"Creative storytelling workspace"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM.jpeg","alt":"Community storytelling activity"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM (1).jpeg","alt":"Creative collaboration"}]'::jsonb,
      '[{"label":"Social engagements","value":"45,000+"},{"label":"Workshops","value":"12"},{"label":"Fellowships","value":"6"}]'::jsonb,
      '[{"quote":"Creative Lab gave us a way to tell our own story and advocate for what matters in our community.","attribution":"Creative Lab participant"}]'::jsonb,
      '[{"title":"Creative brief","url":"./assets/images/PROPOSED PLAN OF ACTION FOR 2026 COMMUNITY OUTREACH (1).pdf","description":"Current content and campaign priorities."}]'::jsonb,
      '[{"title":"Community storytellers"},{"title":"Digital advocates"}]'::jsonb,
      'Creative Lab | White Impact Development Initiative',
      'Media production, storytelling, and creative advocacy that amplifies community voices.',
      5,
      TRUE,
      TRUE
    )
) AS seed(
  slug,
  title,
  summary,
  description,
  body_copy,
  hero_image_url,
  hero_image_alt,
  card_icon,
  card_summary,
  page_url,
  cta_label,
  cta_url,
  status,
  status_label,
  status_detail,
  hero_stats,
  feature_items,
  objectives,
  activities,
  beneficiaries,
  locations,
  timeline,
  gallery,
  impact_metrics,
  stories,
  reports,
  partners,
  seo_title,
  seo_description,
  display_order,
  is_featured,
  is_active
)
WHERE NOT EXISTS (SELECT 1 FROM programs);
