CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(140) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  program_slug VARCHAR(120) REFERENCES programs(slug) ON DELETE SET NULL,
  location VARCHAR(255),
  status VARCHAR(80) NOT NULL DEFAULT 'Active',
  status_label VARCHAR(120),
  status_detail TEXT,
  card_summary TEXT,
  card_icon VARCHAR(20) DEFAULT '●',
  hero_image_url VARCHAR(500),
  hero_image_alt VARCHAR(255),
  body_copy JSONB NOT NULL DEFAULT '[]'::jsonb,
  timeline JSONB NOT NULL DEFAULT '[]'::jsonb,
  objectives JSONB NOT NULL DEFAULT '[]'::jsonb,
  outcomes JSONB NOT NULL DEFAULT '[]'::jsonb,
  media JSONB NOT NULL DEFAULT '[]'::jsonb,
  impact_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
  related_stories JSONB NOT NULL DEFAULT '[]'::jsonb,
  reports JSONB NOT NULL DEFAULT '[]'::jsonb,
  partners JSONB NOT NULL DEFAULT '[]'::jsonb,
  seo_title VARCHAR(255),
  seo_description TEXT,
  display_order INT NOT NULL DEFAULT 0,
  is_featured BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  updated_by INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_projects_program_slug
  ON projects (program_slug);

CREATE INDEX IF NOT EXISTS idx_projects_status
  ON projects (status);

CREATE INDEX IF NOT EXISTS idx_projects_display_order
  ON projects (display_order ASC);

CREATE INDEX IF NOT EXISTS idx_projects_is_active
  ON projects (is_active);

INSERT INTO projects (
  slug,
  title,
  summary,
  description,
  program_slug,
  location,
  status,
  status_label,
  status_detail,
  card_summary,
  card_icon,
  hero_image_url,
  hero_image_alt,
  body_copy,
  timeline,
  objectives,
  outcomes,
  media,
  impact_metrics,
  related_stories,
  reports,
  partners,
  seo_title,
  seo_description,
  display_order,
  is_featured,
  is_active
)
SELECT *
FROM (
  VALUES
    (
      'edu4all-community-outreach-2026',
      'Edu4All Community Outreach',
      'Education access and child protection support for displaced and underserved children.',
      'A community-facing project that brings the Edu4All response into schools, host communities, and safeguarding networks.',
      'edu4all',
      'Kaduna State, Nigeria',
      'Active',
      'Current delivery',
      'Enrollment support, learning materials, and child protection referrals.',
      'Community outreach focused on education and protection.',
      '📖',
      './assets/images/education 1.jpg',
      'Children supported through the Edu4All initiative',
      '["This project connects enrollment support, safeguarding, and caregiver support so children can stay in school.","It is built from the same community priorities that shape the Edu4All program." ]'::jsonb,
      '[{"year":"2025","title":"Project launch","summary":"Community outreach began through school and household engagement."},{"year":"2026","title":"Expansion","summary":"Enrollment and safeguarding work continue across host communities."}]'::jsonb,
      '[{"title":"Increase access","summary":"Help more children enroll and remain in school."},{"title":"Protect children","summary":"Strengthen safeguarding and referral pathways."},{"title":"Support households","summary":"Pair education support with caregiver empowerment."}]'::jsonb,
      '[{"title":"School enrollment","summary":"Direct support for learners returning to class."},{"title":"Protection referral","summary":"Connections to child protection and support services."},{"title":"Learning materials","summary":"Books, uniforms, and classroom supplies."}]'::jsonb,
      '[{"url":"./assets/images/education 1.jpg","alt":"Classroom learning support"},{"url":"./assets/images/education  3.jpg","alt":"Children learning together"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM.jpeg","alt":"Community education outreach"}]'::jsonb,
      '[{"label":"Children reached","value":"2,400+"},{"label":"Communities served","value":"32"},{"label":"Teachers trained","value":"180"}]'::jsonb,
      '[{"title":"Edu4All beneficiary voice","summary":"A caregiver shared that support helped a child return to school and restore stability at home."}]'::jsonb,
      '[{"title":"Community plan of action","url":"./assets/images/PROPOSED PLAN OF ACTION FOR 2026 COMMUNITY OUTREACH (1).pdf","description":"Education and outreach priorities for the current period."}]'::jsonb,
      '[{"title":"UNICEF"},{"title":"GIZ"},{"title":"Kaduna State partners"}]'::jsonb,
      'Edu4All Community Outreach | White Impact Development Initiative',
      'Education access and child protection support for displaced and underserved children.',
      1,
      TRUE,
      TRUE
    ),
    (
      'creative-lab-story-campaigns',
      'Creative Lab Story Campaigns',
      'Media production and storytelling projects that amplify community voices.',
      'A creative production project that turns lived experience into documentaries, social campaigns, and advocacy assets.',
      'creative-lab',
      'Kaduna State and online',
      'Active',
      'Current delivery',
      'Storytelling, media production, and creative advocacy.',
      'Creative media project.',
      '🎬',
      './assets/images/creative-lab.jpeg',
      'Creative storytelling and media production',
      '["This project helps young creators produce media that raises awareness on education access, gender justice, and digital inclusion.","It turns community stories into public-facing campaigns and advocacy materials."]'::jsonb,
      '[{"year":"2025","title":"Creative launch","summary":"The first cohort began production and storytelling support."},{"year":"2026","title":"Campaign growth","summary":"Content distribution and creative partnerships continue to expand."}]'::jsonb,
      '[{"title":"Tell community stories","summary":"Create media that centers lived experience."},{"title":"Grow creative skills","summary":"Give young creators tools and mentorship."},{"title":"Amplify advocacy","summary":"Turn stories into campaigns for change."}]'::jsonb,
      '[{"title":"Media production","summary":"Video, audio, and photography training."},{"title":"Storytelling workshops","summary":"Narrative skills for advocacy and awareness."},{"title":"Social campaigns","summary":"Digital campaigns that amplify community voices."}]'::jsonb,
      '[{"url":"./assets/images/creative-lab.jpeg","alt":"Creative production workspace"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM (1).jpeg","alt":"Storytelling and collaboration"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM (2).jpeg","alt":"Community media engagement"}]'::jsonb,
      '[{"label":"Social engagements","value":"45,000+"},{"label":"Workshops","value":"12"},{"label":"Fellowships","value":"6"}]'::jsonb,
      '[{"title":"Creative Lab participant","summary":"The lab gave us a way to tell our own story and advocate for what matters."}]'::jsonb,
      '[{"title":"Creative brief","url":"./assets/images/PROPOSED PLAN OF ACTION FOR 2026 COMMUNITY OUTREACH (1).pdf","description":"Current content and campaign priorities."}]'::jsonb,
      '[{"title":"Community storytellers"},{"title":"Advocacy partners"}]'::jsonb,
      'Creative Lab Story Campaigns | White Impact Development Initiative',
      'Media production and storytelling projects that amplify community voices.',
      2,
      TRUE,
      TRUE
    ),
    (
      'nextgen-ai-literacy-series',
      'NextGen AI Literacy Series',
      'Ethical AI learning projects focused on data rights, fairness, and participation.',
      'A project that brings responsible AI learning to young people and community advocates.',
      'nextgen-ai',
      'Kaduna State and digital community spaces',
      'Active',
      'Current delivery',
      'AI literacy, data rights, and inclusive innovation.',
      'Digital rights learning project.',
      '🤖',
      './assets/images/ai gen.jpeg',
      'AI literacy and digital inclusion',
      '["The project makes AI easier to understand, question, and shape for community benefit.","It connects technology governance to practical learning and public participation."]'::jsonb,
      '[{"year":"2024","title":"Concept development","summary":"Learning sessions were designed around community questions about AI."},{"year":"2026","title":"Expanded training","summary":"The series continues to support digital literacy and advocacy."}]'::jsonb,
      '[{"title":"Demystify AI","summary":"Make AI understandable for non-technical audiences."},{"title":"Protect rights","summary":"Center fairness, accessibility, and community control."},{"title":"Create opportunity","summary":"Link young people to digital pathways and tools."}]'::jsonb,
      '[{"title":"AI literacy","summary":"Workshops on understanding and using AI."},{"title":"Data rights","summary":"Community ownership and protection of personal data."},{"title":"Policy engagement","summary":"Participation in technology governance discussions."}]'::jsonb,
      '[{"url":"./assets/images/ai gen.jpeg","alt":"AI concept and learning visuals"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM.jpeg","alt":"Digital learning engagement"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.51 PM.jpeg","alt":"Youth technology discussion"}]'::jsonb,
      '[{"label":"Young people trained","value":"5,721+"},{"label":"AI sessions","value":"14"},{"label":"Communities engaged","value":"9"}]'::jsonb,
      '[{"title":"NextGen AI participant","summary":"The session helped us understand AI as something we can question and shape."}]'::jsonb,
      '[{"title":"AI learning brief","url":"./assets/images/2024-wttc-introduction-to-ai.pdf","description":"Current learning and advocacy material."}]'::jsonb,
      '[{"title":"Digital learning communities"},{"title":"Technical collaborators"}]'::jsonb,
      'NextGen AI Literacy Series | White Impact Development Initiative',
      'Ethical AI learning projects focused on data rights, fairness, and participation.',
      3,
      TRUE,
      TRUE
    ),
    (
      'civic-accountability-workshops',
      'Civic Accountability Workshops',
      'Youth-led governance projects focused on transparency, participation, and community monitoring.',
      'A civic engagement project that builds accountability networks and connects grassroots voices to policy spaces.',
      'nextgen-civic-lab',
      'Kaduna State',
      'Active',
      'Current delivery',
      'Transparency, participation, and civic leadership.',
      'Youth civic accountability project.',
      '🏛️',
      './assets/images/nextGen.jpeg',
      'Young people leading civic accountability work',
      '["Participants learn social monitoring, ethical leadership, and practical advocacy methods.","The project supports public accountability through local action and community engagement."]'::jsonb,
      '[{"year":"2025","title":"Civic convening","summary":"Youth-led accountability conversations began."},{"year":"2026","title":"Network expansion","summary":"Civic training continues to grow across communities."}]'::jsonb,
      '[{"title":"Build leadership","summary":"Equip youth with monitoring and advocacy tools."},{"title":"Strengthen voices","summary":"Help communities speak into public systems."},{"title":"Improve accountability","summary":"Support local oversight and public reporting."}]'::jsonb,
      '[{"title":"Social monitoring","summary":"Community based tracking of public services."},{"title":"Transparency advocacy","summary":"Open data and accountability campaigns."},{"title":"Policy engagement","summary":"Connecting grassroots voices to policy spaces."}]'::jsonb,
      '[{"url":"./assets/images/nextGen.jpeg","alt":"Youth civic action and learning"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM.jpeg","alt":"Community accountability engagement"},{"url":"./assets/images/WhatsApp Image 2026-06-24 at 12.14.50 PM (1).jpeg","alt":"Youth discussion"}]'::jsonb,
      '[{"label":"Youth leaders trained","value":"680+"},{"label":"Networks formed","value":"15"},{"label":"Community projects","value":"40"}]'::jsonb,
      '[{"title":"NextGen participant","summary":"I now know how to question public decisions and work with my peers to improve services."}]'::jsonb,
      '[{"title":"Civic action brief","url":"./assets/images/PROPOSED PLAN OF ACTION FOR 2026 COMMUNITY OUTREACH (1).pdf","description":"Current priorities for governance and participation work."}]'::jsonb,
      '[{"title":"Community partners"},{"title":"Accountability groups"}]'::jsonb,
      'Civic Accountability Workshops | White Impact Development Initiative',
      'Youth-led governance projects focused on transparency, participation, and community monitoring.',
      4,
      TRUE,
      TRUE
    )
) AS seed(
  slug,
  title,
  summary,
  description,
  program_slug,
  location,
  status,
  status_label,
  status_detail,
  card_summary,
  card_icon,
  hero_image_url,
  hero_image_alt,
  body_copy,
  timeline,
  objectives,
  outcomes,
  media,
  impact_metrics,
  related_stories,
  reports,
  partners,
  seo_title,
  seo_description,
  display_order,
  is_featured,
  is_active
)
WHERE NOT EXISTS (SELECT 1 FROM projects);
